ALTER TABLE bills ADD COLUMN IF NOT EXISTS local_id VARCHAR(36);
CREATE UNIQUE INDEX IF NOT EXISTS bills_local_id_idx ON bills(local_id) WHERE local_id IS NOT NULL;
ALTER TABLE bills ADD COLUMN IF NOT EXISTS discount_amount NUMERIC(10,2) DEFAULT 0;
